version: "3.6"

services:

  nginx:
    image: "nginx:1-alpine"
    ports:
      - "8080:80"
    volumes:
      - ".:/code:ro"
      - "./docker/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - "php"

  php:
    build:
      context: .
    volumes:
      - ".:/code"
      - "./docker/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "./docker/php.ini:/usr/local/etc/php/php.ini:ro"

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "mysqlRoot"
      MYSQL_DATABASE: "backendTest"
      MYSQL_USER: "backendTest"
      MYSQL_PASSWORD: "backendTest"

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    environment:
      API_URL: "http://localhost:8080/api.yml"
